version: "3.4"

services:

  locustio-master:
    image: "${IMAGE}"
    command: "--host=${HOST} --master"
    ports:
      - target: 8089
        published: 8089
        protocol: tcp
        mode: host
    networks:
      locustio_net:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager

  locustio-worker:
    image: "${IMAGE}"
    command: "--host=${HOST} --slave --master-host=locustio-master"
    deploy:
      mode: replicated
      replicas: 5
    networks:
      locustio_net:
    depends_on:
      - "locustio-master"

networks:
  locustio_net:
    driver: overlay
